name: Schemathesis Services Tests

on:
  push:
  pull_request:

jobs:
  run-schemathesis-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testfile:
          - test_services/test_user_management.py
          - test_services/test_recommendation.py
          - test_services/test_chats.py
          - test_services/test_alert.py
          - test_services/test_feature_switch.py
          - test_services/test_bytebox.py
          - test_services/test_main.py

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libffi-dev build-essential python3-dev

      - name: Upgrade pip and install cffi
        run: |
          pip install --upgrade pip setuptools wheel
          pip install cffi

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "USER_EMAIL=${{ secrets.USER_EMAIL }}" >> $GITHUB_ENV
          echo "USER_PASSWORD=${{ secrets.USER_PASSWORD }}" >> $GITHUB_ENV
          

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run schemathesis test - ${{ matrix.testfile }}
        run: python ${{ matrix.testfile }}

      - name: Debug - list reports folder
        run: ls -R reports

      - name: Sanitize artifact name
        run: |
          SAFE_NAME="${{ matrix.testfile//\//_}}"
          echo "SAFE_ARTIFACT_NAME=$SAFE_NAME" >> $GITHUB_ENV
          
      - name: Upload reports for ${{ matrix.testfile }}
        uses: actions/upload-artifact@v4
        with:
          name: schemathesis-report-${{ env.SAFE_ARTIFACT_NAME }}
          path: test_services