name: Schemathesis Services Tests

on:
  push:
  pull_request:

jobs:
  run-schemathesis-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testfile:
          - schemathesis_testing/test_Services/test_user_management.py
          - schemathesis_testing/test_Services/test_recommendation.py
          - schemathesis_testing/test_Services/test_chats.py
          - schemathesis_testing/test_Services/test_alert.py
          - schemathesis_testing/test_Services/test_feature_switch.py
          - schemathesis_testing/test_Services/test_bytebox.py
          - schemathesis_testing/test_Services/test_main.py

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libffi-dev build-essential python3-dev

      - name: Upgrade pip and install cffi
        run: |
          pip install --upgrade pip setuptools wheel
          pip install cffi

      - name: Install Python dependencies
        run: pip install -r schemathesis_testing/requirements.txt

      - name: Set environment variables
        run: |
          echo "API_EMAIL=${{ secrets.API_EMAIL }}" >> $GITHUB_ENV
          echo "API_PASSWORD=${{ secrets.API_PASSWORD }}" >> $GITHUB_ENV
          echo "API_TOKEN=${{ secrets.API_TOKEN }}" >> $GITHUB_ENV

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Run schemathesis test - ${{ matrix.testfile }}
        run: |
          python ${{ matrix.testfile }}

      - name: Upload reports for ${{ matrix.testfile }}
        uses: actions/upload-artifact@v4
        with:
          name: schemathesis-report-${{ matrix.testfile }}
          path: |
            *.html
            *.xml
